In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('HR_Attrition_Rate.csv')

In [3]:
df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  Gender  JobInvolvement  \
0          2  Life Sciences                        2  Female               3   
1          1  Life Sciences                        3    Male               2   
2          2          Other                        4    Male               2   
3          4  Life Sciences                        4  Female               3   
4          1        Medical                        1    Male               3   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                 8                      0                1               6   
1                10                      3                3              10   
2                 7                      3                3               0   
3                 8                      3                3               8   
4                 6                      3                3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 29 columns]

In [4]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
Gender                      object
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager

In [5]:
df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [6]:
df['Department'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [7]:
df['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [8]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [9]:
df['JobRole'].unique()

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       'Manufacturing Director', 'Healthcare Representative', 'Manager',
       'Sales Representative', 'Research Director', 'Human Resources'],
      dtype=object)

In [10]:
df['MaritalStatus'].unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [11]:
# Drop các cột gây multicollinearity
cols_to_drop = ['TotalWorkingYears', 'JobLevel', 'PercentSalaryHike', 'YearsAtCompany', 'YearsInCurrentRole']
df.drop(columns=cols_to_drop, inplace=True)

In [12]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']

In [13]:
import pandas as pd

X_df = pd.DataFrame(X)
print(X_df.head())

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

print(X_df.head())

   Age     BusinessTravel              Department  DistanceFromHome  \
0   41      Travel_Rarely                   Sales                 1   
1   49  Travel_Frequently  Research & Development                 8   
2   37      Travel_Rarely  Research & Development                 2   
3   33  Travel_Frequently  Research & Development                 3   
4   27      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  Gender  JobInvolvement  \
0          2  Life Sciences                        2  Female               3   
1          1  Life Sciences                        3    Male               2   
2          2          Other                        4    Male               2   
3          4  Life Sciences                        4  Female               3   
4          1        Medical                        1    Male               3   

                 JobRole  ...  MonthlyRate NumCompaniesWorked  \
0        Sales Executive  .

In [14]:
y

0       Yes
1        No
2       Yes
3        No
4        No
       ... 
1465     No
1466     No
1467     No
1468     No
1469     No
Name: Attrition, Length: 1470, dtype: object

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Cột cần OneHot (nhiều hơn 2 loại)
categorical_cols = ['BusinessTravel', 'Department', 'EducationField', 'JobRole']

# Cột chỉ có 2 loại → LabelEncode
binary_cols = ['MaritalStatus', 'Gender']

# Label encode binary columns
df_encoded = df.copy()
for col in binary_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])

# OneHot encode categorical columns
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(drop='first'), categorical_cols)],
    remainder='passthrough'
)

# Áp dụng ColumnTransformer vào df_encoded
X = np.array(ct.fit_transform(df_encoded))  # Sử dụng df_encoded thay vì X


In [16]:
X

array([[0.0, 1.0, 0.0, ..., 1, 0, 5],
       [1.0, 0.0, 1.0, ..., 3, 1, 7],
       [0.0, 1.0, 1.0, ..., 3, 0, 0],
       ...,
       [0.0, 1.0, 1.0, ..., 3, 0, 3],
       [1.0, 0.0, 0.0, ..., 2, 0, 8],
       [0.0, 1.0, 1.0, ..., 4, 1, 2]], dtype=object)

In [17]:
import numpy as np

X = np.delete(X, 18, axis=1)

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
y

array([1, 0, 1, ..., 0, 0, 0])

# Train Model

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 1)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
from catboost import CatBoostClassifier

classifier = CatBoostClassifier() 
classifier.fit(X_train, y_train)

Learning rate set to 0.011041
0:	learn: 0.6853860	total: 137ms	remaining: 2m 16s
1:	learn: 0.6772924	total: 139ms	remaining: 1m 9s
2:	learn: 0.6701490	total: 142ms	remaining: 47.2s
3:	learn: 0.6630427	total: 145ms	remaining: 36s
4:	learn: 0.6559557	total: 147ms	remaining: 29.3s
5:	learn: 0.6489256	total: 150ms	remaining: 24.8s
6:	learn: 0.6414744	total: 153ms	remaining: 21.6s
7:	learn: 0.6339056	total: 155ms	remaining: 19.2s
8:	learn: 0.6266378	total: 158ms	remaining: 17.4s
9:	learn: 0.6204501	total: 161ms	remaining: 15.9s
10:	learn: 0.6141140	total: 163ms	remaining: 14.7s
11:	learn: 0.6088020	total: 165ms	remaining: 13.6s
12:	learn: 0.6027936	total: 168ms	remaining: 12.8s
13:	learn: 0.5968733	total: 171ms	remaining: 12s
14:	learn: 0.5921207	total: 173ms	remaining: 11.4s
15:	learn: 0.5862481	total: 175ms	remaining: 10.8s
16:	learn: 0.5814444	total: 177ms	remaining: 10.2s
17:	learn: 0.5755122	total: 179ms	remaining: 9.78s
18:	learn: 0.5700929	total: 182ms	remaining: 9.38s
19:	learn: 0.5

In [24]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[231   5]
 [ 48  10]]


0.8197278911564626

In [25]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.010553
0:	learn: 0.6855581	total: 2.99ms	remaining: 2.99s
1:	learn: 0.6780286	total: 6.01ms	remaining: 3s
2:	learn: 0.6709412	total: 8.8ms	remaining: 2.92s
3:	learn: 0.6640963	total: 11.3ms	remaining: 2.81s
4:	learn: 0.6574059	total: 14ms	remaining: 2.79s
5:	learn: 0.6505390	total: 16.5ms	remaining: 2.73s
6:	learn: 0.6432860	total: 19.2ms	remaining: 2.72s
7:	learn: 0.6358661	total: 21.1ms	remaining: 2.62s
8:	learn: 0.6291785	total: 23.9ms	remaining: 2.63s
9:	learn: 0.6230268	total: 26.5ms	remaining: 2.63s
10:	learn: 0.6167307	total: 28.9ms	remaining: 2.6s
11:	learn: 0.6104372	total: 31.4ms	remaining: 2.59s
12:	learn: 0.6044421	total: 34ms	remaining: 2.58s
13:	learn: 0.5995131	total: 36.7ms	remaining: 2.58s
14:	learn: 0.5950084	total: 38.8ms	remaining: 2.55s
15:	learn: 0.5894407	total: 41.3ms	remaining: 2.54s
16:	learn: 0.5852893	total: 42.5ms	remaining: 2.46s
17:	learn: 0.5801574	total: 45ms	remaining: 2.45s
18:	learn: 0.5745102	total: 47.6ms	remaining: 2.46s
19:

In [ ]:
from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV

# Khởi tạo mô hình CatBoost
catboost = CatBoostClassifier(verbose=0)

# Định nghĩa các tham số cần tìm kiếm
param_grid = {
    'iterations': [100, 200, 300],  # Số lượng cây
    'learning_rate': [0.01, 0.05, 0.1],  # Tốc độ học
    'depth': [4, 6, 8],  # Độ sâu của cây
    'l2_leaf_reg': [3, 5, 7],  # Regularization
    'subsample': [0.7, 0.8, 0.9],  # Tỷ lệ mẫu
    'colsample_bylevel': [0.7, 0.8, 0.9]  # Tỷ lệ đặc trưng
}

# Sử dụng GridSearchCV để tìm tham số tối ưu
grid_search = GridSearchCV(catboost, param_grid, cv=5, scoring='accuracy')

# Huấn luyện GridSearchCV
grid_search.fit(X_train, y_train)

# In ra các tham số tối ưu và điểm số accuracy tốt nhất
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)
